### PR TITLE
track frameworks base

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by ghost** [comment]
Why do we need to track frameworks/base, this will only cause the need for more dependencies.

**Comment by SuperSandro2000** [comment]
If you try to build twpr for klte using lunch klte it automatically grabs packages/apps/FlipFlap. That one required frameworks/base. 

_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
This is being pulled in by the device tree, so that is where the removing of packages/apps/FlipFlap would need to happen. This seems to be the issue.... its not needed for TWRP, so either remove it from the tree, or download the whole source. https://github.com/LineageOS/android_device_samsung_klte-common/blob/cm-14.1/cm.dependencies#L15(url)

**Comment by SuperSandro2000** [comment]
It would be good for convience but this should be minimal. Thanks for the awnsers.

**Pull request closed without merging**
